### ISSUE TITLE
XSHOOTER spectra

### ISSUE THREAD

**Issue by suvenduat** [jselsing/QuasarComposite#2]
Hello J. Selsing,

I would like to have spectra for each of the seven targets to start a new project where I want to get the line flux of all strong emission lines. I think it is in data/spectra.dat file. But it does not contain wavelength table. Could you please upload or send me (email: suvenduat@gmail.com) your reduced spectra including the wavelength table after all the correction that you already did for your paper?

Many thanks,
Suvendu Rakshit

**Comment by jselsing** [comment]
Hi Suvendu.

Sorry for the late reply. 

I added the file regularized.dat, located in py/data/regularized.dat. This file should contain the un-normalized spectra along with the wavelength array. It is organised in 8 column with the first column being the wavelength array and the next seven the spectra. All spectra have been moved to rest, resampled onto af common grid and corrected for galactic extinction. I hope this is what you wanted, otherwise please let me know. 

All the  best, 

Jonatan
